wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724007644
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      3:
      - 23
      4: 3.11.6
      5: 0.17.1
      6: 4.41.2
      8:
      - 1
      - 6
      13: linux-x86_64
